local ScreenGui = Instance.new("ScreenGui",game:GetService("CoreGui"))
ScreenGui.Name = "NukeShop"
local Frame1 = Instance.new("Frame",ScreenGui)
Frame1.Size = UDim2.new(1,0,1,0)
local Padding = Instance.new("UIPadding",ScreenGui)
Padding.PaddingBottom = UDim.new(0.1,0)
Padding.PaddingRight = UDim.new(0.1,0)
Padding.PaddingLeft = UDim.new(0.1,0)
Padding.PaddingTop = UDim.new(0.1,0)
